# Gemini Chat
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.1-flash-lite

# Gemini Embeddings
# Gemini Embeddings
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.text.model=gemini-embedding-2
spring.ai.google.genai.embedding.text.dimensions=1536

# PostgreSQL
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/incidentiq
spring.datasource.username=incidentiq
spring.datasource.password=incidentiq
spring.datasource.driver-class-name=org.postgresql.Driver

# PGVector
spring.ai.vectorstore.pgvector.initialize-schema=true

server.port=8080